[[frontend]]
name = "yew"
crates-io = "Yew"
homepage = "https://yew.rs"
repo = "https://github.com/yewstack/yew"
vdom = true
ssr = false

[[frontend]]
name = "Seed"
crates-io = "seed"
homepage = "http://seed-rs.org/"
repo = "https://github.com/seed-rs/seed"
vdom = true
ssr = false

[[frontend]]
name = "sauron"
repo = "https://github.com/ivanceras/sauron"
crates-io = "sauron"
vdom = true
ssr = true

[[frontend]]
name = "mogwai"
repo = "https://github.com/schell/mogwai"
crates-io = "mogwai"
vdom = false
ssr = true

[[frontend]]
name = "dominator"
repo = "https://github.com/Pauan/rust-dominator"
crates-io = "dominator"
vdom = false
ssr = false

[[frontend]]
name = "Sycamore"
homepage = "https://sycamore-rs.netlify.app"
repo = "https://github.com/sycamore-rs/sycamore"
crates-io = "sycamore"
vdom = false
ssr = true

[[frontend]]
name = "Dioxus"
homepage = "https://dioxuslabs.com/"
repo = "https://github.com/dioxuslabs/dioxus"
crates-io = "dioxus"
vdom = true
ssr = true

[[frontend]]
name = "MoonZoon"
homepage = "http://moonzoon.rs/"
repo = "https://github.com/MoonZoon/MoonZoon"
vdom = false

[[frontend]]
name = "Silkenweb"
crates-io = "silkenweb"
repo = "https://github.com/silkenweb/silkenweb"
vdom = false
ssr = true

[[frontend]]
homepage = "https://chinedufn.github.io/percy/"
name = "percy"
repo = "https://github.com/chinedufn/percy"
ssr = true
vdom = true
outdated = false

[[frontend]]
name = "frender"
crates-io = "frender"
homepage = "https://frender-rs.github.io/frender/"
repo = "https://github.com/frender-rs/frender"
vdom = true
ssr = false
outdated = true

[[frontend]]
outdated = true
crates-io = "dodrio"
name = "dodrio"
repo = "https://github.com/fitzgen/dodrio"

[[frontend]]
outdated = true
name = "draco"
repo = "https://github.com/utkarshkukreti/draco"

[[frontend]]
outdated = true
name = "dumle"
repo = "https://github.com/axelf4/dumle"

[[frontend]]
outdated = true
name = "mika"
repo = "https://gitlab.com/limira-rs/mika"

[[frontend]]
outdated = true
name = "ruukh"
repo = "https://github.com/csharad/ruukh"

[[frontend]]
outdated = true
name = "smithy"
crates-io = "smithy"
repo = "https://github.com/rbalicki2/smithy"
homepage = "https://www.smithy.rs/"

[[frontend]]
outdated = true
name = "squark"
repo = "https://github.com/rail44/squark"

[[frontend]]
outdated = true
name = "stdweb"
crates-io = "stdweb"
repo = "https://github.com/koute/stdweb"

[[frontend]]
outdated = true
name = "willow"
repo = "https://github.com/sindreij/willow"

[[template]]
name = "sailfish"
homepage = "https://sailfish.netlify.app"
repo = "https://github.com/Kogia-sima/sailfish/"
crates-io = "sailfish"

[[template]]
name = "tera"
homepage = "https://tera.netlify.com/"
repo = "https://github.com/Keats/tera"
crates-io = "tera"

[[template]]
name = "mustache"
repo = "https://github.com/nickel-org/rust-mustache"
crates-io = "mustache"

[[template]]
name = "liquid"
repo = "https://github.com/cobalt-org/liquid-rust"

[[template]]
name = "handlebars"
repo = "https://github.com/sunng87/handlebars-rust"
crates-io = "handlebars"

[[template]]
name = "horrorshow"
repo = "https://github.com/Stebalien/horrorshow-rs"
crates-io = "horrorshow"

[[template]]
name = "maud"
repo = "https://github.com/lfairy/maud"
homepage = "https://lfairy.gitbooks.io/maud/content"
crates-io = "maud"

[[template]]
name = "askama"
repo = "https://github.com/djc/askama"
crates-io = "askama"

[[template]]
name = "stpl"
repo = "https://github.com/dpc/stpl"

[[template]]
name = "ructe"
repo = "https://github.com/kaj/ructe"
crates-io = "ructe"

[[template]]
name = "typed-html"
repo = "https://github.com/bodil/typed-html"
crates-io = "typed-html"

[[server]]
name = "hyper"
homepage = "http://hyper.rs/"
repo = "https://github.com/hyperium/hyper"
crates-io = "hyper"
low-level = true
outdated = false
async = true
http2 = true
https = true
client = true

[[server]]
name = "tiny-http"
repo = "https://github.com/tiny-http/tiny-http"
crates-io = "tiny_http"
low-level = true
outdated = false
async = false
http2 = false
https = true
client = false

[[server]]
name = "actix-http"
homepage = "https://github.com/actix/actix-web/tree/master/actix-http"
repo = "https://github.com/actix/actix-web"
crates-io = "actix-http"
low-level = true
outdated = false
async = true
http2 = true
https = true
client = true

[[websocket]]
name = "tungstenite"
crates-io = "tungstenite"
repo = "https://github.com/snapview/tungstenite-rs"
server = true
client = true
async = true

[[websocket]]
name = "tokio-tungstenite"
crates-io = "tokio-tungstenite"
repo = "https://github.com/snapview/tokio-tungstenite"
server = true
client = true
async = true

[[websocket]]
name = "actix-web"
crates-io = "actix-web-actors"
repo = "https://github.com/actix/actix-web"
homepage = "https://actix.rs/docs/websockets/"
server = true
client = true
async = true

[[websocket]]
name = "ws-rs"
repo = "https://github.com/housleyjk/ws-rs"
crates-io = "ws"
server = true
client = true
async = true

[[websocket]]
name = "websocket"
repo = "https://github.com/websockets-rs/rust-websocket"
homepage = "https://websockets-rs.github.io/rust-websocket/"
crates-io = "websocket"
server = true
client = true
async = true
outdated = true
